<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-Tensors-与-Operations" data-toc-modified-id="1.-Tensors-与-Operations-1">1. Tensors 与 Operations</a></span></li><li><span><a href="#2.-Tensors-与-NumPy" data-toc-modified-id="2.-Tensors-与-NumPy-2">2. Tensors 与 NumPy</a></span></li><li><span><a href="#3.-Type-conversions（类型转换）" data-toc-modified-id="3.-Type-conversions（类型转换）-3">3. Type conversions（类型转换）</a></span></li><li><span><a href="#4.-Variables" data-toc-modified-id="4.-Variables-4">4. Variables</a></span></li><li><span><a href="#5.-其他数据结构" data-toc-modified-id="5.-其他数据结构-5">5. 其他数据结构</a></span><ul class="toc-item"><li><span><a href="#5.1-Sparse-tensors-(tf.SparseTensor)" data-toc-modified-id="5.1-Sparse-tensors-(tf.SparseTensor)-5.1">5.1 Sparse tensors (<code>tf.SparseTensor</code>)</a></span></li></ul></li></ul></div>

In [1]:
import os

import numpy as np
import tensorflow as tf
from IPython.core.interactiveshell import InteractiveShell
from tensorflow import keras

InteractiveShell.ast_node_interactivity = 'all'
os.environ['CUDA_VISIBLE_DEVICES'] = '3'

In [2]:
print("TensorFlow version:", tf.__version__)
print("keras version:", keras.__version__)

TensorFlow version: 2.3.0
keras version: 2.4.0


**<font color='crimson'>TF's API revolves around tensors, which flow from operation to operation -- hence the name TensorFlow.</font>**

tensor 与 NumPy 的 ndarray 非常相似，通常是一个多维数组（multi-dimensional array），但也支持 scalar（单个值，如 42）。

tensor 在创建自定义 loss functions、metrics、layers 等时非常重要。

## 1. Tensors 与 Operations

**可以使用 `tf.constant()` 来创建 tensor。**

In [3]:
# matrix
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
# scalar
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

和 NumPy 的 ndarray 一样，**`tf.Tensor`** 也有 shape 和 data type:

In [5]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
# Returns a 1-D integer tensor representing the shape of `input`.
tf.shape(t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [8]:
t.dtype

tf.int32

Indexing 的使用方式同在 NumPy 中：

In [9]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [10]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [11]:
t[..., 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

<font color='blue'>All sorts of tensor operations are available.</font>

In [12]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
t + 10

# Equivalent to
tf.add(t, 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [14]:
t - 10

# Equivalent to
tf.subtract(t, 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-6, -5, -4]], dtype=int32)>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-9, -8, -7],
       [-6, -5, -4]], dtype=int32)>

In [15]:
t * 10

# Equivalent to
tf.multiply(t, 10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]], dtype=int32)>

In [16]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [17]:
t @ tf.transpose(t)

# Equivalent to
tf.matmul(t, tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

- TensorFlow 支持所有的基本数学操作（如，`tf.add()`、`tf.mulitply()`、`tf.square()`、`tf.exp()`、`tf.sqrt()` 等），大部分操作在 NumPy 中也有（如，`tf.reshape()`、`tf.squeeze()`、`tf.tile()` 等）。


- **有一些函数在 NumPy 中和在 TensorFlow 中的名称不一样。**如，`tf.reduce_mean()`，`tf.reduce_sum()`，`tf.reduce_max()` 和 `tf.math.log()` 分别等同于 `np.mean()`，`np.sum()`，`np.max()` 和 `np.log()`。

**名称不一样是有原因的。**如：

- 在 TensorFlow 中必须使用 `tf.transpose()`，而不是像在 NumPy 中使用 `.T` attribute。

  - In TensorFlow, a new tensor is created with its own copy of the transposed data.
  
  - In NumPy, `t.T` is just a transposed view on the same data.


- 叫 `tf.reduce_sum()` 是因为它的 GPU kernel（GPU 实现）使用 **<font color='red'> reduce algorithm</font>**，这不能保证元素相加的顺序。由于 32 位 float 精度有限，每次调用该方法的结果可能不同。`tf.reduce_mean()` 类似，但是 `tf.reduce_max()` 的结果时绝对的。

<br>

**<font color='crimson'>Many functions and classes have aliases. This allows TensorFlow to have concise (简洁的) names for the most common operations while preserving well-organized packages.</font>** 如，`tf.add()` 和 `tf.math.add()` 是相同的函数。

> `tf.math.log()` 没有叫做 `tf.log()` 的别名。因为会与 logging 混淆。

<div class="alert alert-block alert-info">
    <center><b>Keras 低级 API</b></center><br>
    Keras 有自己的低级 API，在 <code>keras.backend</code> 中。它包含像 <code>square</code>、<code>exp</code> 和 <code>sqrt()</code> 这样的函数。
    
在 <code>tf.keras</code> 中，这些函数通常会调用相应的 TensorFlow op。

如果想写可移植到其他 keras implementations 的代码，就应该这使用这些 keras 函数。然而，这些函数只是 TensorFlow 函数中的一部分。
</div>

In [18]:
from tensorflow.keras import backend as K

In [19]:
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

## 2. Tensors 与 NumPy

**<font color='crimson'>Tensors play nice with NumPy.</font>**

- 可以使用 NumPy ndarry 来创建 tensor，反之亦然。


- TensorFlow op 可应用到 NumPy ndarray 上，也可以对 tensor 应用 NumPy op。

In [20]:
a = np.array([2., 4, 5.])
a

array([2., 4., 5.])

In [21]:
a.dtype

dtype('float64')

In [22]:
# Create tensor from a NumPy array
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [23]:
t.numpy()

# Or
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [24]:
# Apply TF op to ndarray
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [25]:
# Apply NumPy op to tensor
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

<div class="alert alert-block alert-warning">
<b>NumPy 默认使用 64 位精度，而 TensorFlow 默认使用 32 位精度。</b> 这是因为对于神经网络，32 位精度通常足够了，同时运行速度更快，使用更少的 RAM。
    
<b>当使用 NumPy ndarray 来创建 tensor 时，确保设置 <code>dtye=tf.float32</code>。
</div>

## 3. Type conversions（类型转换）

**<font color='crimson'>类型转换会严重地影响性能（significantly hurt performance），并且在自动完成的时候，很容易被忽略。</font>** 因此，TensorFlow 不会自动地执行任何类型转换——如果在 2 个类型不兼容的（incompatible） tensor 上执行 op，会 raise exception。

In [32]:
# float tensor, integer tensor
try:
    tf.constant(2.) + tf.constant(10)
except tf.errors.InvalidArgumentError as e:
    print(e)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]


In [33]:
# 32-bit float + 64-bit float
try:
    tf.constant(2.) + tf.constant(10, dtype=tf.float64)
except tf.errors.InvalidArgumentError as e:
    print(e)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]


不能自动地转换类型确实有点烦人，但绝对是有原因的。

**可以使用 `tf.cast()` 来做类型转换：**

In [34]:
# Cast a tensor to a new type
t2 = tf.constant(40., dtype=tf.float64)
t2 = tf.cast(x=t2, dtype=tf.float32)

t2 + tf.constant(2.)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## 4. Variables

**<font color='crimson'>`tf.Tensor` 是不可变的（immutable）——不能被修改。</font>**

这意味着它不能用做 NN 的 weights，因为在 BP 时需要轻微调整（tweak） weights。而且，其他参数（如，momentum optimizer 需要 track 过去的 gradients）。

此时，需要 **`tf.Variable`**。

In [35]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

`tf.Variable` 的行为和 `tf.Tensor` 非常类似：

- 可以使用同样的 op


- 与 NumPy 能互动的很好


- 对类型有要求（picky with types）

但是，**<font color='crimson'>使用 `assign()` 方法可以 in place 修改 `tf.Variable`。</font>**（或 `assign_add()` 或 `assign_sub()`，会給 `tf.Variable` increment 或 decrement 给定值。）

而且，可以使用 cell's/slice's 的 `assign()` 方法（直接赋值是行不通的）/`scatter_update()`方法/ `scatter_nd_update()` 方法来修改 individual cell/slice。

In [36]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [37]:
v.assign(2 * v)

v  # 被修改啦

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [40]:
v.assign(tf.ones(shape=(2, 3)))

v  # 被修改啦

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [42]:
v.assign_add(tf.ones(shape=(2, 3)))

v  # 被修改啦

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)>

In [43]:
v[0, 1].assign(100)

v  # 被修改啦

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  2., 100.,   2.],
       [  2.,   2.,   2.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  2., 100.,   2.],
       [  2.,   2.,   2.]], dtype=float32)>

In [46]:
v[:, 0].assign([-1, -1])

v

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ -1., 100.,   2.],
       [ -1.,   2.,   2.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ -1., 100.,   2.],
       [ -1.,   2.,   2.]], dtype=float32)>

In [47]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[-100, -100])

v

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[-100.,  100.,    2.],
       [  -1.,    2., -100.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-100.,  100.,    2.],
       [  -1.,    2., -100.]], dtype=float32)>

In [52]:
v.assign(tf.ones(shape=(2, 3)))

v  # 被修改啦

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [53]:
v - 100

v  # 没有修改

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-99., -99., -99.],
       [-99., -99., -99.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [54]:
v.assign_add(v - 100)

v

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[-98., -98., -98.],
       [-98., -98., -98.]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-98., -98., -98.],
       [-98., -98., -98.]], dtype=float32)>

<div class="alert alert-block alert-info">
    <b>实际中，很少需要去手动创建 variables，因为 Keras 提供了类似于 <code>add_weight()</code> 的方法来处理这些。而且，模型的参数通常由 optimizer 直接更新，所以很少需要手动更新 variables。</b>
</div>

## 5. 其他数据结构

TensorFlow 还支持其他数据结构。

To Do.

### 5.1 Sparse tensors (`tf.SparseTensor`)